/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package edu.progavud.taller3.view;

import java.awt.Image;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.SwingUtilities;

/**
 *
 * @author Miguel
 */
public class PanelCarrera extends javax.swing.JPanel {

    /**
     * Creates new form PanelInicio
     */
    public PanelCarrera(int numCorredores) {
        initComponents();
        setSize(new java.awt.Dimension(750, (150 * numCorredores) + 100));
        lblsCompetidores = new ArrayList<>();
        cargarImagenFondo();
    }

    public void cargarImagenFondo() {
        ImageIcon originalIcon = new ImageIcon(getClass().getResource("/imagenes/super_mario_bros_1_1_wallpaper_hd_flat_by_wougie89_d6toae7-pre.jpg"));

        //Escala la imagen a 150×150 píxeles, así que se puede cambiar como quieran :D
        Image scaledImage = originalIcon.getImage()
                .getScaledInstance(750, getSize().height - 100, Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(scaledImage);

        lblImagen.setIcon(scaledIcon);
        lblImagen.setBounds(0, 0, 750, getSize().height - 100);
        repaint();
    }

    public void crearImagenCompetidor(String nombreImagen) {
        //Carga la imagen con el nombre del archivo, lo dejo así para despues tin ponerlo como metodo del MVC y etc :D
        ImageIcon originalIcon = new ImageIcon(getClass().getResource("/imagenes/" + nombreImagen));

        //Escala la imagen a 150×150 píxeles, así que se puede cambiar como quieran :D
        Image scaledImage = originalIcon.getImage()
                .getScaledInstance(150, 150, Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(scaledImage);

        JLabel lblCompetidor = new javax.swing.JLabel(scaledIcon);
        lblsCompetidores.add(lblCompetidor);
        System.out.println("Se añadio un competidor");
    }

    public void colocarCompetidores() {
        int nextY = getHeight() - 250;
        for (int i = 0; i < lblsCompetidores.size(); i++) {
            elementosCarrera.add(lblsCompetidores.get(i), 0); //asi queda de primeritas :D
            lblsCompetidores.get(i).setBounds(0, nextY, 150, 150); //Si cambiaron tamaño de la imagen lo hacen aca tambien por favor >:(
            nextY -= 150;
        }
        revalidate();
        repaint();
    }

    public void moverCompetidor(int indexCompetidor, int posicionesAvanzadas, int distanciaCarrera) {
        SwingUtilities.invokeLater(() -> {
            JLabel lbl = lblsCompetidores.get(indexCompetidor);

            int posXActual = lbl.getX();
            int posYActual = lbl.getY();

            // ancho máximo de desplazamiento en píxeles
            int posXMax = 750 - lbl.getWidth();

            // cuántos píxeles vale cada “posición”
            double pixelesPorPosicion = (double) posXMax / distanciaCarrera;

            // cálculo del desplazamiento en pixeles según posicionesAvanzadas
            int desplazamiento = (int) Math.round(posicionesAvanzadas * pixelesPorPosicion);

            // nueva X, acotada entre 0 y posXMax
            int nuevaPosX = Math.max(0,
                    Math.min(posXActual + desplazamiento, posXMax));

            // mover y repintar
            lbl.setLocation(nuevaPosX, posYActual);
            System.out.println("el label se movio, nueva ubicacion: " + lbl.getLocation());
            repaint();
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelBotones = new javax.swing.JPanel();
        btnAccidente1 = new javax.swing.JButton();
        btnImpulsar2 = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        lblInformacion = new javax.swing.JLabel();
        elementosCarrera = new javax.swing.JLayeredPane();
        lblImagen = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(750, 429));
        setLayout(new java.awt.BorderLayout());

        PanelBotones.setBackground(new java.awt.Color(15, 89, 45));
        PanelBotones.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 30, 20));

        btnAccidente1.setText("ACCIDENTE1");
        PanelBotones.add(btnAccidente1);

        btnImpulsar2.setText("IMPULSAR2");
        PanelBotones.add(btnImpulsar2);

        btnSalir.setText("SALIR");
        btnSalir.setToolTipText("");
        PanelBotones.add(btnSalir);
        PanelBotones.add(lblInformacion);

        add(PanelBotones, java.awt.BorderLayout.PAGE_END);

        elementosCarrera.add(lblImagen);
        lblImagen.setBounds(0, 0, 750, 366);

        add(elementosCarrera, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    public ArrayList<javax.swing.JLabel> lblsCompetidores;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel PanelBotones;
    public javax.swing.JButton btnAccidente1;
    public javax.swing.JButton btnImpulsar2;
    public javax.swing.JButton btnSalir;
    public javax.swing.JLayeredPane elementosCarrera;
    public javax.swing.JLabel lblImagen;
    public javax.swing.JLabel lblInformacion;
    // End of variables declaration//GEN-END:variables
}
