/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.progavud.taller3.view;

import edu.progavud.taller3.controller.ControlVentana;
import javax.swing.JOptionPane;

/**
 *
 * @author Miguel
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private ControlVentana cVentana;
    
    public VentanaPrincipal(ControlVentana cVentana) {
        this.cVentana = cVentana;
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setVisible(true);
    }
    
    public void cargarPanelInicio() {
        this.getContentPane().removeAll();
        panelCanvas = new PanelInicio();
        setSize(panelCanvas.getPreferredSize());
        add(panelCanvas);
        cVentana.asignarOyentesPanelInicio();
        revalidate();
        repaint();
    }
    
    public void cargarPanelCarrera(int numJugadores){
        this.getContentPane().removeAll();
        panelCanvas = new PanelCarrera(numJugadores);
        setSize(panelCanvas.getPreferredSize());
        add(panelCanvas);
        ((PanelCarrera) panelCanvas).cargarImagenFondo();
        cVentana.crearImagenesCompetidores();
        ((PanelCarrera) panelCanvas).colocarCompetidores();
        cVentana.asignarOyentesPanelCarrera();
        revalidate();
        repaint();
    }
    
    public void cargarPanelFinal(String mensajeGanador) { 
        this.getContentPane().removeAll();
        panelCanvas = new PanelFinal();
        setSize(panelCanvas.getPreferredSize());
        ((PanelFinal) panelCanvas).txtaGanador.setText(mensajeGanador);
        add(panelCanvas);
        cVentana.asignarOyentesPanelCarrera();
        revalidate();
        repaint();
    }
    
    
    public String mostrarDigiteNumCompetidores() {
        return JOptionPane.showInputDialog(null, "Digite el numero de competidores que desea:",  JOptionPane.DEFAULT_OPTION);
    }
    
    public String mostrarDigiteNomCompetidor() {
        return JOptionPane.showInputDialog(null, "Digite el nombre del periquin que va a competir:",  JOptionPane.DEFAULT_OPTION);
    }
    
    public void mostrarMensajeJOptionPane(String mensaje) {
        JOptionPane.showMessageDialog(null, mensaje);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCanvas = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout panelCanvasLayout = new javax.swing.GroupLayout(panelCanvas);
        panelCanvas.setLayout(panelCanvasLayout);
        panelCanvasLayout.setHorizontalGroup(
            panelCanvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        panelCanvasLayout.setVerticalGroup(
            panelCanvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 429, Short.MAX_VALUE)
        );

        getContentPane().add(panelCanvas, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel panelCanvas;
    // End of variables declaration//GEN-END:variables
}
